repositories:
  - name: dts
    url: https://helm.dts-stn.com
{{- if or (eq .Environment.Name "prod-blue") (eq .Environment.Name "prod-green") }}
context: EsDCDTSRG-K8S
{{ else }}
context: EsDCDTSDevRG-K8S
{{ end }}

environments:
  dev:
  review:
  prod-blue:
  prod-green:

releases:
  # Benefit Service
  - name: benefit-service-{{ .Environment.Name }}
    chart: ../helm/charts/benefit-service
    version: 0.0.1
    values:
      - overrides/benefitService.yaml.gotmpl
    labels:
      category: dts
      app: benefit-service
      tier: server
    {{ if (eq .Environment.Name "review") }}
    namespace: benefit-service-{{ .Environment.Name }}-{{ requiredEnv "PULL_REQUEST" }}
    {{ else }}
    namespace: benefit-service-{{ .Environment.Name }}
    {{ end }}
    installed: true
    wait: false
    force: false


  - name: keycloak-bs-{{ .Environment.Name }}
    chart: dts/dts-keycloak
    version: 9.0.1
    namespace: security-bs-{{ .Environment.Name }}
    values:
      - overrides/keycloak/keycloak.yaml.gotmpl
    labels:
        category: security
        app: keycloak
        tier: full
    installed: true
    wait: false
    force: false