basePath: /
definitions:
  models.LifeJourney:
    properties:
      description:
        type: string
      description_fr:
        type: string
      id:
        type: integer
      related_benefits:
        items:
          type: string
        type: array
      title:
        type: string
      title_fr:
        type: string
    type: object
  renderings.LifeJourneyResponse:
    properties:
      lifejourneys:
        description: Life Journey ID
        items:
          $ref: '#/definitions/models.LifeJourney'
        type: array
    type: object
  renderings.QPSError:
    properties:
      error_code:
        type: string
    type: object
host: '[TBD]'
info:
  contact: {}
  description: This service returns information about lifejourneys
  title: Benefit Service
  version: "1.0"
paths:
  /healthcheck:
    get:
      description: Returns Healthy
      operationId: healthcheck
      responses:
        "200":
          description: Healthy
          schema:
            type: string
      summary: Returns Healthy
  /lifejourney:
    get:
      consumes:
      - application/json
      operationId: Life Journey
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.LifeJourneyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.QPSError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.QPSError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.QPSError'
      summary: Request Info on Life Journey
swagger: "2.0"
