basePath: /
definitions:
  models.Benefits:
    properties:
      benefit_details:
        items:
          $ref: '#/definitions/models.FieldDetails'
        type: array
      description:
        type: string
      id:
        type: string
      related_benefits:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  models.FieldDetails:
    properties:
      field_long_description:
        type: string
      field_short_description:
        type: string
      fieldname:
        type: string
    type: object
  models.LifeJourney:
    properties:
      description:
        type: string
      id:
        type: string
      lifejourney_details:
        items:
          $ref: '#/definitions/models.FieldDetails'
        type: array
      related_benefits:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  renderings.BenefitServiceError:
    properties:
      error_code:
        type: string
    type: object
  renderings.BenefitsResponse:
    properties:
      benefits:
        description: Life Journey ID
        items:
          $ref: '#/definitions/models.Benefits'
        type: array
    type: object
  renderings.LifeJourneyResponse:
    properties:
      lifejourneys:
        description: Life Journey ID
        items:
          $ref: '#/definitions/models.LifeJourney'
        type: array
    type: object
host: https://benefit-service-dev.dev.dts-stn.com
info:
  contact: {}
  description: This service returns information about Benefits
  title: Benefit Service
  version: "1.0"
paths:
  /benefits:
    get:
      consumes:
      - application/json
      operationId: benefits
      parameters:
      - description: The language the response should be in. Defaults to English.
          English and French supported.
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.BenefitsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
      summary: Request Info on Benefits
  /healthcheck:
    get:
      description: Returns Healthy
      operationId: healthcheck
      responses:
        "200":
          description: Healthy
          schema:
            type: string
      summary: Returns Healthy
  /lifejourney:
    get:
      consumes:
      - application/json
      operationId: life-journey
      parameters:
      - description: The language the response should be in. Defaults to English.
          English and French supported.
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.LifeJourneyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
      summary: Request Info on Life Journey
swagger: "2.0"
