basePath: /
definitions:
  models.Benefits:
    properties:
      api_url:
        type: string
      benefit_key:
        type: string
      benefit_tags:
        items:
          type: string
        type: array
      benefit_type:
        type: string
      description:
        type: string
      id:
        type: integer
      long_description:
        type: string
      redirect_url:
        type: string
      related_benefits:
        items:
          type: string
        type: array
      service_type:
        type: string
      title:
        type: string
    type: object
  renderings.BenefitServiceError:
    properties:
      error_code:
        type: string
    type: object
  renderings.BenefitsResponse:
    properties:
      benefit:
        $ref: '#/definitions/models.Benefits'
      benefits:
        description: Life Journey ID
        items:
          $ref: '#/definitions/models.Benefits'
        type: array
    type: object
host: https://benefit-service-dev.dev.dts-stn.com
info:
  contact: {}
  description: This service returns information about Benefits
  title: Benefit Service
  version: "1.0"
paths:
  /benefits:
    get:
      consumes:
      - application/json
      operationId: benefits
      parameters:
      - description: The language the response should be in. Defaults to English.
          English and French supported.
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.BenefitsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
      summary: Request Info on Benefits
  /healthcheck:
    get:
      description: Returns Healthy
      operationId: healthcheck
      responses:
        "200":
          description: Healthy
          schema:
            type: string
      summary: Returns Healthy
swagger: "2.0"
