basePath: /
definitions:
  models.Benefits:
    properties:
      benefit_details:
        items:
          $ref: '#/definitions/models.FieldDetails'
        type: array
      description:
        type: string
      id:
        type: string
      long_description:
        type: string
      related_benefits:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  models.FieldDetails:
    properties:
      field_long_description:
        type: string
      field_short_description:
        type: string
      fieldname:
        type: string
    type: object
  models.LifeJourney:
    properties:
      description:
        type: string
      id:
        type: string
      lifejourney_details:
        items:
          $ref: '#/definitions/models.FieldDetails'
        type: array
      related_benefits:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  models.Question:
    properties:
      answer:
        type: string
      dependency_of:
        description: List of which benefits the question is a dependency of
        items:
          type: string
        type: array
      description:
        type: string
      id:
        type: string
      openfisca_ids:
        description: The OpenFisca input variable name(s) attributed to this question
        items:
          type: string
        type: array
    type: object
  renderings.BenefitQuestionsResponse:
    properties:
      benefit_list:
        description: Array of specific benefits to get the questions for
        items:
          type: string
        type: array
      life_journeys:
        description: Array of life journeys, which represent a subset of benefits
        items:
          type: string
        type: array
      question_list:
        description: List of answered priority questions
        items:
          $ref: '#/definitions/models.Question'
        type: array
      request_date:
        description: Date period for request in ms since epoch
        type: integer
    type: object
  renderings.BenefitServiceError:
    properties:
      error_code:
        type: string
    type: object
  renderings.BenefitsResponse:
    properties:
      benefits:
        description: Life Journey ID
        items:
          $ref: '#/definitions/models.Benefits'
        type: array
    type: object
  renderings.LifeJourneyResponse:
    properties:
      lifejourneys:
        description: Life Journey ID
        items:
          $ref: '#/definitions/models.LifeJourney'
        type: array
    type: object
host: https://benefit-service-dev.dev.dts-stn.com
info:
  contact: {}
  description: This service returns information about Benefits
  title: Benefit Service
  version: "1.0"
paths:
  /benefits:
    get:
      consumes:
      - application/json
      operationId: benefits
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.BenefitsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
      summary: Request Info on Benefits
  /getquestions:
    get:
      consumes:
      - application/json
      description: Returns question dependencies for requested benefits
      operationId: GetBenefitQuestions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.BenefitQuestionsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
      summary: Returns question dependencies for requested benefits
  /healthcheck:
    get:
      description: Returns Healthy
      operationId: healthcheck
      responses:
        "200":
          description: Healthy
          schema:
            type: string
      summary: Returns Healthy
  /lifejourney:
    get:
      consumes:
      - application/json
      operationId: life-journey
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderings.LifeJourneyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
      summary: Request Info on Life Journey
  /lifejourneys/:id/benefits:
    get:
      consumes:
      - application/json
      operationId: life-journey-benefits
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Benefits'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/renderings.BenefitServiceError'
      summary: Request Info on Life Journey Related Benefits
swagger: "2.0"
